---
services:
  tailscale_subnet_router:
    image: tailscale/tailscale:stable
    container_name: tailscale_subnet_router
    restart: always
    network_mode: "host"
    volumes:
      - /var/lib:/var/lib
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - UTILITY_SERVER_USERNAME=${UTILITY_SERVER_USERNAME}
      - UTILITY_SERVER_PASSWORD=${UTILITY_SERVER_PASSWORD}
      - TAILSCALE_AUTH_KEY=${TAILSCALE_AUTH_KEY}
